server:
  port: 5000

feign:
  okhttp:
    enable: true
  client:
    config:
      default:
        connectTimeout: 100
        readTimeout: 60000

existing_apis:
  host: localhost
  port: 3001
  endpoint: product